### ISSUE TITLE
Angular project not working in production

### ISSUE THREAD

**Issue by jadhavsuraj2207** [retejs/examples#15]
Hi,
I am facing an issue when i try to build angular project in production.
giving me following error
`Configuration 'production' could not be found in project 'app'.
Error: Configuration 'production' could not be found in project 'app'.
    at Architect.getBuilderConfiguration (/home/suraj/Downloads/examples-master/Angular/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect-legacy.js:127:23)
    at ServeCommand.runSingleTarget (/home/suraj/Downloads/examples-master/Angular/node_modules/@angular/cli/models/architect-command.js:160:45)
    at ServeCommand.runArchitectTarget (/home/suraj/Downloads/examples-master/Angular/node_modules/@angular/cli/models/architect-command.js:201:35)
    at ServeCommand.run (/home/suraj/Downloads/examples-master/Angular/node_modules/@angular/cli/commands/serve-impl.js:24:21)
    at ServeCommand.validateAndRun (/home/suraj/Downloads/examples-master/Angular/node_modules/@angular/cli/models/command.js:124:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
`
Any solution ?
Thanks.

**Comment by Ni55aN** [comment]
Please point out what are the differences between your project and the current example?
